export type CategoryId =
  | "vegetable"
  | "mushroom_seaweed"
  | "meat"
  | "seafood"
  | "egg_dairy_soy"
  | "staple_flour"
  | "dry_canned_frozen";

export type Category = {
  id: CategoryId;
  label: string;
};

export type SeedIngredient = {
  name: string;
  category: CategoryId;
};

export type SeedSeasoning = {
  name: string;
  enabled: boolean;
};

export const CATEGORIES: Category[] = [
  { id: "vegetable", label: "野菜" },
  { id: "mushroom_seaweed", label: "きのこ・海藻" },
  { id: "meat", label: "肉" },
  { id: "seafood", label: "魚介" },
  { id: "egg_dairy_soy", label: "卵・乳・豆" },
  { id: "staple_flour", label: "主食・粉" },
  { id: "dry_canned_frozen", label: "乾物・缶詰・冷凍" },
];

export const INGREDIENTS: SeedIngredient[] = [
  { name: "玉ねぎ", category: "vegetable" },
  { name: "長ねぎ", category: "vegetable" },
  { name: "にんにく", category: "vegetable" },
  { name: "生姜", category: "vegetable" },
  { name: "じゃがいも", category: "vegetable" },
  { name: "にんじん", category: "vegetable" },
  { name: "キャベツ", category: "vegetable" },
  { name: "白菜", category: "vegetable" },
  { name: "もやし", category: "vegetable" },
  { name: "トマト", category: "vegetable" },
  { name: "ミニトマト", category: "vegetable" },
  { name: "きゅうり", category: "vegetable" },
  { name: "なす", category: "vegetable" },
  { name: "ピーマン", category: "vegetable" },
  { name: "パプリカ", category: "vegetable" },
  { name: "ブロッコリー", category: "vegetable" },
  { name: "ほうれん草", category: "vegetable" },
  { name: "小松菜", category: "vegetable" },
  { name: "チンゲン菜", category: "vegetable" },
  { name: "空心菜", category: "vegetable" },
  { name: "豆苗", category: "vegetable" },
  { name: "ニラ", category: "vegetable" },
  { name: "レタス", category: "vegetable" },
  { name: "大根", category: "vegetable" },
  { name: "かぼちゃ", category: "vegetable" },
  { name: "さつまいも", category: "vegetable" },
  { name: "里芋", category: "vegetable" },
  { name: "れんこん", category: "vegetable" },
  { name: "ごぼう", category: "vegetable" },
  { name: "アスパラガス", category: "vegetable" },
  { name: "オクラ", category: "vegetable" },
  { name: "ズッキーニ", category: "vegetable" },
  { name: "セロリ", category: "vegetable" },
  { name: "パクチー", category: "vegetable" },
  { name: "苦瓜", category: "vegetable" },
  { name: "とうもろこし", category: "vegetable" },
  { name: "枝豆", category: "vegetable" },
  { name: "アボカド", category: "vegetable" },
  { name: "いんげん", category: "vegetable" },
  { name: "長芋", category: "vegetable" },
  { name: "にんにくの芽", category: "vegetable" },
  { name: "小ねぎ", category: "vegetable" },
  { name: "カリフラワー", category: "vegetable" },
  { name: "レモン", category: "vegetable" },
  { name: "しいたけ", category: "mushroom_seaweed" },
  { name: "えのき", category: "mushroom_seaweed" },
  { name: "しめじ", category: "mushroom_seaweed" },
  { name: "まいたけ", category: "mushroom_seaweed" },
  { name: "エリンギ", category: "mushroom_seaweed" },
  { name: "マッシュルーム", category: "mushroom_seaweed" },
  { name: "きくらげ", category: "mushroom_seaweed" },
  { name: "わかめ", category: "mushroom_seaweed" },
  { name: "海苔", category: "mushroom_seaweed" },
  { name: "ひじき", category: "mushroom_seaweed" },
  { name: "豚バラ", category: "meat" },
  { name: "豚こま", category: "meat" },
  { name: "豚ロース", category: "meat" },
  { name: "豚ひき肉", category: "meat" },
  { name: "鶏もも", category: "meat" },
  { name: "鶏むね", category: "meat" },
  { name: "鶏ひき肉", category: "meat" },
  { name: "手羽元", category: "meat" },
  { name: "手羽先", category: "meat" },
  { name: "ささみ", category: "meat" },
  { name: "牛こま", category: "meat" },
  { name: "牛ステーキ肉", category: "meat" },
  { name: "合いびき肉", category: "meat" },
  { name: "ベーコン", category: "meat" },
  { name: "ハム", category: "meat" },
  { name: "ソーセージ", category: "meat" },
  { name: "ラム肉", category: "meat" },
  { name: "スペアリブ", category: "meat" },
  { name: "鮭", category: "seafood" },
  { name: "さば", category: "seafood" },
  { name: "さんま", category: "seafood" },
  { name: "あじ", category: "seafood" },
  { name: "たら", category: "seafood" },
  { name: "ぶり", category: "seafood" },
  { name: "まぐろ", category: "seafood" },
  { name: "えび", category: "seafood" },
  { name: "いか", category: "seafood" },
  { name: "たこ", category: "seafood" },
  { name: "あさり", category: "seafood" },
  { name: "ホタテ", category: "seafood" },
  { name: "ちくわ", category: "seafood" },
  { name: "卵", category: "egg_dairy_soy" },
  { name: "牛乳", category: "egg_dairy_soy" },
  { name: "バター", category: "egg_dairy_soy" },
  { name: "チーズ", category: "egg_dairy_soy" },
  { name: "ピザ用チーズ", category: "egg_dairy_soy" },
  { name: "生クリーム", category: "egg_dairy_soy" },
  { name: "ヨーグルト", category: "egg_dairy_soy" },
  { name: "豆腐", category: "egg_dairy_soy" },
  { name: "厚揚げ", category: "egg_dairy_soy" },
  { name: "油揚げ", category: "egg_dairy_soy" },
  { name: "納豆", category: "egg_dairy_soy" },
  { name: "豆乳", category: "egg_dairy_soy" },
  { name: "腐竹", category: "egg_dairy_soy" },
  { name: "豆腐干", category: "egg_dairy_soy" },
  { name: "ごはん", category: "staple_flour" },
  { name: "パスタ", category: "staple_flour" },
  { name: "うどん", category: "staple_flour" },
  { name: "そば", category: "staple_flour" },
  { name: "中華麺", category: "staple_flour" },
  { name: "そうめん", category: "staple_flour" },
  { name: "食パン", category: "staple_flour" },
  { name: "餃子の皮", category: "staple_flour" },
  { name: "春巻きの皮", category: "staple_flour" },
  { name: "小麦粉", category: "staple_flour" },
  { name: "片栗粉", category: "staple_flour" },
  { name: "パン粉", category: "staple_flour" },
  { name: "米粉", category: "staple_flour" },
  { name: "オートミール", category: "staple_flour" },
  { name: "ツナ缶", category: "dry_canned_frozen" },
  { name: "トマト缶", category: "dry_canned_frozen" },
  { name: "コーン缶", category: "dry_canned_frozen" },
  { name: "サバ缶", category: "dry_canned_frozen" },
  { name: "ひよこ豆缶", category: "dry_canned_frozen" },
  { name: "春雨", category: "dry_canned_frozen" },
  { name: "高野豆腐", category: "dry_canned_frozen" },
  { name: "切り干し大根", category: "dry_canned_frozen" },
  { name: "干し椎茸", category: "dry_canned_frozen" },
  { name: "かつお節", category: "dry_canned_frozen" },
  { name: "昆布", category: "dry_canned_frozen" },
  { name: "梅干し", category: "dry_canned_frozen" },
  { name: "ザーサイ", category: "dry_canned_frozen" },
  { name: "キムチ", category: "dry_canned_frozen" },
  { name: "冷凍餃子", category: "dry_canned_frozen" },
  { name: "冷凍ミックスベジタブル", category: "dry_canned_frozen" },
  { name: "冷凍うどん", category: "dry_canned_frozen" },
  { name: "冷凍シーフードミックス", category: "dry_canned_frozen" },
];

export const SEASONINGS: SeedSeasoning[] = [
  { name: "塩", enabled: true },
  { name: "こしょう", enabled: true },
  { name: "砂糖", enabled: true },
  { name: "醤油", enabled: true },
  { name: "味噌", enabled: true },
  { name: "酢", enabled: true },
  { name: "みりん", enabled: true },
  { name: "料理酒", enabled: true },
  { name: "サラダ油", enabled: true },
  { name: "ごま油", enabled: true },
  { name: "オリーブオイル", enabled: true },
  { name: "マヨネーズ", enabled: true },
  { name: "ケチャップ", enabled: true },
  { name: "中濃ソース", enabled: false },
  { name: "めんつゆ", enabled: false },
  { name: "鶏がらスープの素", enabled: true },
  { name: "コンソメ", enabled: false },
  { name: "オイスターソース", enabled: true },
  { name: "豆板醤", enabled: true },
  { name: "甜麺醤", enabled: false },
  { name: "花椒", enabled: false },
  { name: "五香粉", enabled: false },
  { name: "カレー粉", enabled: false },
  { name: "ナンプラー", enabled: false },
  { name: "白ごま", enabled: true },
  { name: "ラー油", enabled: false },
  { name: "バジル", enabled: false },
  { name: "ローリエ", enabled: false },
  { name: "顆粒だし", enabled: true },
  { name: "ポン酢", enabled: true },
  { name: "鷹の爪", enabled: true },
  { name: "カレールー", enabled: false },
  { name: "焼肉のたれ", enabled: false },
  { name: "黒酢", enabled: true },
  { name: "バルサミコ酢", enabled: true },
  { name: "老抽", enabled: true },
];
